package api

import (
	"context"
	"errors"

	"connectrpc.com/connect"

	apiv1 "github.com/tinkerrc/volunteer/proto/api/v1" // generated by protoc-gen-go
)

func (s *APIServer) UpdateVolunteerProfile(
	ctx context.Context,
	req *connect.Request[apiv1.UpdateVolunteerProfileRequest],
) (*connect.Response[apiv1.UpdateVolunteerProfileResponse], error) {
	v, err := s.ensureVolunteer(ctx)
	if err != nil {
		return nil, err
	}
	m := req.Msg
	update := s.Db.Volunteer.UpdateOneID(v.ID)
	if m.FirstName != nil {
		update = update.SetFirstName(*m.FirstName)
	}
	if m.MiddleName != nil {
		update = update.SetMiddleName(*m.MiddleName)
	}
	if m.LastName != nil {
		update = update.SetLastName(*m.LastName)
	}
	if m.Phone != nil {
		update = update.SetPhone(*m.Phone)
	}
	if m.Address != nil {
		update = update.SetAddress(*m.Address)
	}
	_, err = update.Save(ctx)
	if err != nil {
		return nil, connect.NewError(connect.CodeInternal, errors.New("failed to update volunteer"))
	}
	res := connect.NewResponse(&apiv1.UpdateVolunteerProfileResponse{})
	return res, nil
}
