package api

import (
	"context"

	"connectrpc.com/connect"

	apiv1 "github.com/tinkerrc/volunteer/proto/api/v1" // generated by protoc-gen-go
)

func (s *APIServer) CreateVolunteer(
	ctx context.Context,
	req *connect.Request[apiv1.CreateVolunteerRequest],
) (*connect.Response[apiv1.CreateVolunteerResponse], error) {
	err := s.ensureAdmin(ctx)
	if err != nil {
		return nil, err
	}

	msg := req.Msg
	v, err := s.Db.Volunteer.Create().
		SetEmail(msg.Email).
		SetFirstName(msg.FirstName).
		SetMiddleName(msg.MiddleName).
		SetLastName(msg.LastName).
		SetPhone(msg.Phone).
		SetAddress(msg.Address).
		SetNotes("").
		Save(ctx)
	if err != nil {
		// return nil, connect.NewError(connect.CodeInternal, errors.New("failed to create volunteer"))
		return nil, connect.NewError(connect.CodeInternal, err)
	}

	res := connect.NewResponse(&apiv1.CreateVolunteerResponse{
		Id: v.ID.String(),
	})
	return res, nil
}
