package api

import (
	"context"
	"errors"

	"connectrpc.com/connect"

	"github.com/google/uuid"
	apiv1 "github.com/tinkerrc/volunteer/proto/api/v1" // generated by protoc-gen-go
)

func (s *APIServer) DeleteTraining(
	ctx context.Context,
	req *connect.Request[apiv1.DeleteTrainingRequest],
) (*connect.Response[apiv1.DeleteTrainingResponse], error) {
	err := s.ensureAdmin(ctx)
	if err != nil {
		return nil, connect.NewError(connect.CodePermissionDenied, errors.New("unauthorized"))
	}
	m := req.Msg
	tid, err := uuid.Parse(m.Id)
	if err != nil {
		return nil, connect.NewError(connect.CodeInvalidArgument, errors.New("invalid training id"))
	}
	err = s.Db.Training.DeleteOneID(tid).Exec(ctx)
	if err != nil {
		return nil, connect.NewError(connect.CodeNotFound, errors.New("training not found"))
	}
	res := connect.NewResponse(&apiv1.DeleteTrainingResponse{})
	return res, nil
}
