package api

import (
	"context"
	"errors"

	"connectrpc.com/connect"

	apiv1 "github.com/tinkerrc/volunteer/proto/api/v1" // generated by protoc-gen-go
)

func (s *APIServer) CreateCert(
	ctx context.Context,
	req *connect.Request[apiv1.CreateCertRequest],
) (*connect.Response[apiv1.CreateCertResponse], error) {
	err := s.ensureAdmin(ctx)
	if err != nil {
		return nil, connect.NewError(connect.CodePermissionDenied, errors.New("unauthorized"))
	}
	m := req.Msg
	c, err := s.Db.Cert.Create().SetName(m.Name).SetDescription(m.Description).Save(ctx)
	if err != nil {
		return nil, connect.NewError(connect.CodeInternal, errors.New("could not create cert"))
	}
	res := connect.NewResponse(&apiv1.CreateCertResponse{
		Id: c.ID.String(),
	})
	return res, nil
}
