package api

import (
	"context"

	"connectrpc.com/connect"

	apiv1 "github.com/tinkerrc/volunteer/proto/api/v1" // generated by protoc-gen-go
)

// TODO: implement
func (s *APIServer) ListEventVolunteers(
	ctx context.Context,
	req *connect.Request[apiv1.ListEventVolunteersRequest],
) (*connect.Response[apiv1.ListEventVolunteersResponse], error) {
	// u, ok := authn.GetInfo(ctx).(ent.User)
	// if !ok {
	// 	return nil, authn.Errorf("unauthenticated")
	// }

	res := connect.NewResponse(&apiv1.ListEventVolunteersResponse{
		Volunteers: []*apiv1.Volunteer{},
	})
	return res, nil
}
