package api

import (
	"context"

	"connectrpc.com/connect"

	apiv1 "github.com/tinkerrc/volunteer/proto/api/v1" // generated by protoc-gen-go
)

// TODO: implement
func (s *APIServer) GetVolunteer(
	ctx context.Context,
	req *connect.Request[apiv1.GetVolunteerRequest],
) (*connect.Response[apiv1.GetVolunteerResponse], error) {
	v, err := s.ensureVolunteer(ctx)
	if err != nil {
		return nil, err
	}
	p, err := s.getVolunteerProto(ctx, v)
	if err != nil {
		return nil, err
	}
	res := connect.NewResponse(&apiv1.GetVolunteerResponse{
		Volunteer: p,
	})
	return res, nil
}
