package main

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"os"
	"strings"

	"connectrpc.com/authn"
	"entgo.io/ent/dialect"
	"github.com/tinkerrc/volunteer/ent"
	"github.com/tinkerrc/volunteer/server/api"
	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"

	_ "github.com/lib/pq"

	apiv1connect "github.com/tinkerrc/volunteer/proto/api/v1/apiv1connect" // generated by protoc-gen-connect-go
)

func main() {
	adminEmail := os.Getenv("ADMIN")
	if !strings.Contains(adminEmail, "@") {
		log.Fatalf("ADMIN environment variable does not contain valid email")
	}

	host := os.Getenv("PG_HOST")
	port := os.Getenv("PG_PORT")
	user := os.Getenv("PG_USER")
	pass := os.Getenv("PG_PASS")
	dbname := os.Getenv("PG_DBNAME")
	dataSource := fmt.Sprintf("host=%s port=%s user=%s password=%s dbname=%s sslmode=disable", host, port, user, pass, dbname)
	cl, err := ent.Open(dialect.Postgres, dataSource)
	if err != nil {
		log.Fatalf("failed connecting to database: %v", err)
	}
	defer cl.Close()
	log.Println("connected to database")

	ctx := context.Background()
	if err := cl.Schema.Create(ctx); err != nil {
		log.Fatalf("migration failed: %v", err)
	}
	log.Println("schema migration done")

	server := &api.APIServer{Db: cl, AdminEmail: adminEmail}
	mux := http.NewServeMux()
	path, handler := apiv1connect.NewVolunteerServiceHandler(server)
	mux.Handle(path, handler)

	middleware := authn.NewMiddleware(api.Authenticate(cl))

	// Use h2c so we can serve HTTP/2 without TLS.
	handler = h2c.NewHandler(mux, &http2.Server{})
	handler = middleware.Wrap(handler)
	http.ListenAndServe(
		"localhost:8080",
		handler,
	)
}
