// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/tinkerrc/volunteer/ent/eventvolunteer"
	"github.com/tinkerrc/volunteer/ent/predicate"
)

// EventVolunteerDelete is the builder for deleting a EventVolunteer entity.
type EventVolunteerDelete struct {
	config
	hooks    []Hook
	mutation *EventVolunteerMutation
}

// Where appends a list predicates to the EventVolunteerDelete builder.
func (evd *EventVolunteerDelete) Where(ps ...predicate.EventVolunteer) *EventVolunteerDelete {
	evd.mutation.Where(ps...)
	return evd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (evd *EventVolunteerDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, evd.sqlExec, evd.mutation, evd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (evd *EventVolunteerDelete) ExecX(ctx context.Context) int {
	n, err := evd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (evd *EventVolunteerDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(eventvolunteer.Table, sqlgraph.NewFieldSpec(eventvolunteer.FieldID, field.TypeUUID))
	if ps := evd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, evd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	evd.mutation.done = true
	return affected, err
}

// EventVolunteerDeleteOne is the builder for deleting a single EventVolunteer entity.
type EventVolunteerDeleteOne struct {
	evd *EventVolunteerDelete
}

// Where appends a list predicates to the EventVolunteerDelete builder.
func (evdo *EventVolunteerDeleteOne) Where(ps ...predicate.EventVolunteer) *EventVolunteerDeleteOne {
	evdo.evd.mutation.Where(ps...)
	return evdo
}

// Exec executes the deletion query.
func (evdo *EventVolunteerDeleteOne) Exec(ctx context.Context) error {
	n, err := evdo.evd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{eventvolunteer.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (evdo *EventVolunteerDeleteOne) ExecX(ctx context.Context) {
	if err := evdo.Exec(ctx); err != nil {
		panic(err)
	}
}
