// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/google/uuid"
	"github.com/tinkerrc/volunteer/ent/schema"
	"github.com/tinkerrc/volunteer/ent/timelog"
	"github.com/tinkerrc/volunteer/ent/user"
	"github.com/tinkerrc/volunteer/ent/volunteer"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	timelogFields := schema.TimeLog{}.Fields()
	_ = timelogFields
	// timelogDescID is the schema descriptor for id field.
	timelogDescID := timelogFields[0].Descriptor()
	// timelog.DefaultID holds the default value on creation for the id field.
	timelog.DefaultID = timelogDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
	volunteerFields := schema.Volunteer{}.Fields()
	_ = volunteerFields
	// volunteerDescID is the schema descriptor for id field.
	volunteerDescID := volunteerFields[0].Descriptor()
	// volunteer.DefaultID holds the default value on creation for the id field.
	volunteer.DefaultID = volunteerDescID.Default.(func() uuid.UUID)
}
