// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/tinkerrc/volunteer/ent/timelog"
)

// TimeLog is the model entity for the TimeLog schema.
type TimeLog struct {
	config
	// ID of the ent.
	ID           int `json:"id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TimeLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case timelog.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TimeLog fields.
func (tl *TimeLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case timelog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			tl.ID = int(value.Int64)
		default:
			tl.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TimeLog.
// This includes values selected through modifiers, order, etc.
func (tl *TimeLog) Value(name string) (ent.Value, error) {
	return tl.selectValues.Get(name)
}

// Update returns a builder for updating this TimeLog.
// Note that you need to call TimeLog.Unwrap() before calling this method if this TimeLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (tl *TimeLog) Update() *TimeLogUpdateOne {
	return NewTimeLogClient(tl.config).UpdateOne(tl)
}

// Unwrap unwraps the TimeLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (tl *TimeLog) Unwrap() *TimeLog {
	_tx, ok := tl.config.driver.(*txDriver)
	if !ok {
		panic("ent: TimeLog is not a transactional entity")
	}
	tl.config.driver = _tx.drv
	return tl
}

// String implements the fmt.Stringer.
func (tl *TimeLog) String() string {
	var builder strings.Builder
	builder.WriteString("TimeLog(")
	builder.WriteString(fmt.Sprintf("id=%v", tl.ID))
	builder.WriteByte(')')
	return builder.String()
}

// TimeLogs is a parsable slice of TimeLog.
type TimeLogs []*TimeLog
