// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/tinkerrc/volunteer/ent/cert"
	"github.com/tinkerrc/volunteer/ent/predicate"
	"github.com/tinkerrc/volunteer/ent/training"
	"github.com/tinkerrc/volunteer/ent/volunteer"
)

// TrainingQuery is the builder for querying Training entities.
type TrainingQuery struct {
	config
	ctx           *QueryContext
	order         []training.OrderOption
	inters        []Interceptor
	predicates    []predicate.Training
	withVolunteer *VolunteerQuery
	withCert      *CertQuery
	withFKs       bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TrainingQuery builder.
func (tq *TrainingQuery) Where(ps ...predicate.Training) *TrainingQuery {
	tq.predicates = append(tq.predicates, ps...)
	return tq
}

// Limit the number of records to be returned by this query.
func (tq *TrainingQuery) Limit(limit int) *TrainingQuery {
	tq.ctx.Limit = &limit
	return tq
}

// Offset to start from.
func (tq *TrainingQuery) Offset(offset int) *TrainingQuery {
	tq.ctx.Offset = &offset
	return tq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tq *TrainingQuery) Unique(unique bool) *TrainingQuery {
	tq.ctx.Unique = &unique
	return tq
}

// Order specifies how the records should be ordered.
func (tq *TrainingQuery) Order(o ...training.OrderOption) *TrainingQuery {
	tq.order = append(tq.order, o...)
	return tq
}

// QueryVolunteer chains the current query on the "volunteer" edge.
func (tq *TrainingQuery) QueryVolunteer() *VolunteerQuery {
	query := (&VolunteerClient{config: tq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(training.Table, training.FieldID, selector),
			sqlgraph.To(volunteer.Table, volunteer.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, training.VolunteerTable, training.VolunteerColumn),
		)
		fromU = sqlgraph.SetNeighbors(tq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCert chains the current query on the "cert" edge.
func (tq *TrainingQuery) QueryCert() *CertQuery {
	query := (&CertClient{config: tq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(training.Table, training.FieldID, selector),
			sqlgraph.To(cert.Table, cert.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, training.CertTable, training.CertColumn),
		)
		fromU = sqlgraph.SetNeighbors(tq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Training entity from the query.
// Returns a *NotFoundError when no Training was found.
func (tq *TrainingQuery) First(ctx context.Context) (*Training, error) {
	nodes, err := tq.Limit(1).All(setContextOp(ctx, tq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{training.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tq *TrainingQuery) FirstX(ctx context.Context) *Training {
	node, err := tq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Training ID from the query.
// Returns a *NotFoundError when no Training ID was found.
func (tq *TrainingQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = tq.Limit(1).IDs(setContextOp(ctx, tq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{training.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tq *TrainingQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := tq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Training entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Training entity is found.
// Returns a *NotFoundError when no Training entities are found.
func (tq *TrainingQuery) Only(ctx context.Context) (*Training, error) {
	nodes, err := tq.Limit(2).All(setContextOp(ctx, tq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{training.Label}
	default:
		return nil, &NotSingularError{training.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tq *TrainingQuery) OnlyX(ctx context.Context) *Training {
	node, err := tq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Training ID in the query.
// Returns a *NotSingularError when more than one Training ID is found.
// Returns a *NotFoundError when no entities are found.
func (tq *TrainingQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = tq.Limit(2).IDs(setContextOp(ctx, tq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{training.Label}
	default:
		err = &NotSingularError{training.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tq *TrainingQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := tq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Trainings.
func (tq *TrainingQuery) All(ctx context.Context) ([]*Training, error) {
	ctx = setContextOp(ctx, tq.ctx, ent.OpQueryAll)
	if err := tq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Training, *TrainingQuery]()
	return withInterceptors[[]*Training](ctx, tq, qr, tq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tq *TrainingQuery) AllX(ctx context.Context) []*Training {
	nodes, err := tq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Training IDs.
func (tq *TrainingQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if tq.ctx.Unique == nil && tq.path != nil {
		tq.Unique(true)
	}
	ctx = setContextOp(ctx, tq.ctx, ent.OpQueryIDs)
	if err = tq.Select(training.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tq *TrainingQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := tq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tq *TrainingQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tq.ctx, ent.OpQueryCount)
	if err := tq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tq, querierCount[*TrainingQuery](), tq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tq *TrainingQuery) CountX(ctx context.Context) int {
	count, err := tq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tq *TrainingQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tq.ctx, ent.OpQueryExist)
	switch _, err := tq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tq *TrainingQuery) ExistX(ctx context.Context) bool {
	exist, err := tq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TrainingQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tq *TrainingQuery) Clone() *TrainingQuery {
	if tq == nil {
		return nil
	}
	return &TrainingQuery{
		config:        tq.config,
		ctx:           tq.ctx.Clone(),
		order:         append([]training.OrderOption{}, tq.order...),
		inters:        append([]Interceptor{}, tq.inters...),
		predicates:    append([]predicate.Training{}, tq.predicates...),
		withVolunteer: tq.withVolunteer.Clone(),
		withCert:      tq.withCert.Clone(),
		// clone intermediate query.
		sql:  tq.sql.Clone(),
		path: tq.path,
	}
}

// WithVolunteer tells the query-builder to eager-load the nodes that are connected to
// the "volunteer" edge. The optional arguments are used to configure the query builder of the edge.
func (tq *TrainingQuery) WithVolunteer(opts ...func(*VolunteerQuery)) *TrainingQuery {
	query := (&VolunteerClient{config: tq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tq.withVolunteer = query
	return tq
}

// WithCert tells the query-builder to eager-load the nodes that are connected to
// the "cert" edge. The optional arguments are used to configure the query builder of the edge.
func (tq *TrainingQuery) WithCert(opts ...func(*CertQuery)) *TrainingQuery {
	query := (&CertClient{config: tq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tq.withCert = query
	return tq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		StartDate time.Time `json:"start_date,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Training.Query().
//		GroupBy(training.FieldStartDate).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tq *TrainingQuery) GroupBy(field string, fields ...string) *TrainingGroupBy {
	tq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TrainingGroupBy{build: tq}
	grbuild.flds = &tq.ctx.Fields
	grbuild.label = training.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		StartDate time.Time `json:"start_date,omitempty"`
//	}
//
//	client.Training.Query().
//		Select(training.FieldStartDate).
//		Scan(ctx, &v)
func (tq *TrainingQuery) Select(fields ...string) *TrainingSelect {
	tq.ctx.Fields = append(tq.ctx.Fields, fields...)
	sbuild := &TrainingSelect{TrainingQuery: tq}
	sbuild.label = training.Label
	sbuild.flds, sbuild.scan = &tq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TrainingSelect configured with the given aggregations.
func (tq *TrainingQuery) Aggregate(fns ...AggregateFunc) *TrainingSelect {
	return tq.Select().Aggregate(fns...)
}

func (tq *TrainingQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tq); err != nil {
				return err
			}
		}
	}
	for _, f := range tq.ctx.Fields {
		if !training.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tq.path != nil {
		prev, err := tq.path(ctx)
		if err != nil {
			return err
		}
		tq.sql = prev
	}
	return nil
}

func (tq *TrainingQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Training, error) {
	var (
		nodes       = []*Training{}
		withFKs     = tq.withFKs
		_spec       = tq.querySpec()
		loadedTypes = [2]bool{
			tq.withVolunteer != nil,
			tq.withCert != nil,
		}
	)
	if tq.withVolunteer != nil || tq.withCert != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, training.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Training).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Training{config: tq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := tq.withVolunteer; query != nil {
		if err := tq.loadVolunteer(ctx, query, nodes, nil,
			func(n *Training, e *Volunteer) { n.Edges.Volunteer = e }); err != nil {
			return nil, err
		}
	}
	if query := tq.withCert; query != nil {
		if err := tq.loadCert(ctx, query, nodes, nil,
			func(n *Training, e *Cert) { n.Edges.Cert = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (tq *TrainingQuery) loadVolunteer(ctx context.Context, query *VolunteerQuery, nodes []*Training, init func(*Training), assign func(*Training, *Volunteer)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Training)
	for i := range nodes {
		if nodes[i].training_volunteer == nil {
			continue
		}
		fk := *nodes[i].training_volunteer
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(volunteer.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "training_volunteer" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (tq *TrainingQuery) loadCert(ctx context.Context, query *CertQuery, nodes []*Training, init func(*Training), assign func(*Training, *Cert)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Training)
	for i := range nodes {
		if nodes[i].training_cert == nil {
			continue
		}
		fk := *nodes[i].training_cert
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(cert.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "training_cert" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (tq *TrainingQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tq.querySpec()
	_spec.Node.Columns = tq.ctx.Fields
	if len(tq.ctx.Fields) > 0 {
		_spec.Unique = tq.ctx.Unique != nil && *tq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tq.driver, _spec)
}

func (tq *TrainingQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(training.Table, training.Columns, sqlgraph.NewFieldSpec(training.FieldID, field.TypeUUID))
	_spec.From = tq.sql
	if unique := tq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tq.path != nil {
		_spec.Unique = true
	}
	if fields := tq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, training.FieldID)
		for i := range fields {
			if fields[i] != training.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tq *TrainingQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tq.driver.Dialect())
	t1 := builder.Table(training.Table)
	columns := tq.ctx.Fields
	if len(columns) == 0 {
		columns = training.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tq.sql != nil {
		selector = tq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tq.ctx.Unique != nil && *tq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range tq.predicates {
		p(selector)
	}
	for _, p := range tq.order {
		p(selector)
	}
	if offset := tq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TrainingGroupBy is the group-by builder for Training entities.
type TrainingGroupBy struct {
	selector
	build *TrainingQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tgb *TrainingGroupBy) Aggregate(fns ...AggregateFunc) *TrainingGroupBy {
	tgb.fns = append(tgb.fns, fns...)
	return tgb
}

// Scan applies the selector query and scans the result into the given value.
func (tgb *TrainingGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tgb.build.ctx, ent.OpQueryGroupBy)
	if err := tgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TrainingQuery, *TrainingGroupBy](ctx, tgb.build, tgb, tgb.build.inters, v)
}

func (tgb *TrainingGroupBy) sqlScan(ctx context.Context, root *TrainingQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tgb.fns))
	for _, fn := range tgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tgb.flds)+len(tgb.fns))
		for _, f := range *tgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TrainingSelect is the builder for selecting fields of Training entities.
type TrainingSelect struct {
	*TrainingQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ts *TrainingSelect) Aggregate(fns ...AggregateFunc) *TrainingSelect {
	ts.fns = append(ts.fns, fns...)
	return ts
}

// Scan applies the selector query and scans the result into the given value.
func (ts *TrainingSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ts.ctx, ent.OpQuerySelect)
	if err := ts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TrainingQuery, *TrainingSelect](ctx, ts.TrainingQuery, ts, ts.inters, v)
}

func (ts *TrainingSelect) sqlScan(ctx context.Context, root *TrainingQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ts.fns))
	for _, fn := range ts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
