// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Cert is the predicate function for cert builders.
type Cert func(*sql.Selector)

// Event is the predicate function for event builders.
type Event func(*sql.Selector)

// EventVolunteer is the predicate function for eventvolunteer builders.
type EventVolunteer func(*sql.Selector)

// TimeLog is the predicate function for timelog builders.
type TimeLog func(*sql.Selector)

// Training is the predicate function for training builders.
type Training func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Volunteer is the predicate function for volunteer builders.
type Volunteer func(*sql.Selector)
