// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Certification is the predicate function for certification builders.
type Certification func(*sql.Selector)

// Event is the predicate function for event builders.
type Event func(*sql.Selector)

// TimeLog is the predicate function for timelog builders.
type TimeLog func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Volunteer is the predicate function for volunteer builders.
type Volunteer func(*sql.Selector)
